name:        linearmap-hmatrix
version:     0.1.0.0
description: an hmatrix backend to linearmap-category

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fprint-potential-instances

  dependencies:
  - constrained-categories
  - free-vector-spaces
  - hmatrix
  - linearmap-category
  - tagged
  - vector
  - vector-space

tests:
  linearmap-hmatrix-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - linearmap-hmatrix
    - hspec
    - QuickCheck
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - hspec-discover
